/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdf_ndkthread_MainActivity */

#ifndef _Included_com_asdf_ndkthread_MainActivity
#define _Included_com_asdf_ndkthread_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_asdf_ndkthread_MainActivity
 * Method:    initNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_asdf_ndkthread_MainActivity_initNative
  (JNIEnv *, jobject);

/*
 * Class:     com_asdf_ndkthread_MainActivity
 * Method:    freeNative
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_asdf_ndkthread_MainActivity_freeNative
  (JNIEnv *, jobject);

/*
 * Class:     com_asdf_ndkthread_MainActivity
 * Method:    posixThreads
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_asdf_ndkthread_MainActivity_posixThreads
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_asdf_ndkthread_MainActivity
 * Method:    nativeWorker
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_asdf_ndkthread_MainActivity_nativeWorker
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
