/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdf_myndkdemo_MainActivity */

#ifndef _Included_com_asdf_myndkdemo_MainActivity
#define _Included_com_asdf_myndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
