/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdf_echosocket_LocalSocketActivity_ServerTask */

#ifndef _Included_com_asdf_echosocket_LocalSocketActivity_ServerTask
#define _Included_com_asdf_echosocket_LocalSocketActivity_ServerTask
#ifdef __cplusplus
extern "C" {
#endif
#undef com_asdf_echosocket_LocalSocketActivity_ServerTask_MIN_PRIORITY
#define com_asdf_echosocket_LocalSocketActivity_ServerTask_MIN_PRIORITY 1L
#undef com_asdf_echosocket_LocalSocketActivity_ServerTask_NORM_PRIORITY
#define com_asdf_echosocket_LocalSocketActivity_ServerTask_NORM_PRIORITY 5L
#undef com_asdf_echosocket_LocalSocketActivity_ServerTask_MAX_PRIORITY
#define com_asdf_echosocket_LocalSocketActivity_ServerTask_MAX_PRIORITY 10L
#ifdef __cplusplus
}
#endif
#endif
