/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_asdf_echosocket_EchoClientActivity_ClientTask */

#ifndef _Included_com_asdf_echosocket_EchoClientActivity_ClientTask
#define _Included_com_asdf_echosocket_EchoClientActivity_ClientTask
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
